package main

// City is the canonical, server-owned shape for a retirement city.
// JSON keys intentionally match the frontend TypeScript `City` type.
type City struct {
	City        string   `json:"city"`
	Country     string   `json:"country"`
	Region      string   `json:"region"`
	MonthlyCost int      `json:"monthlyCost"`
	Lifestyle   string   `json:"lifestyle"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	// ExpenseShares is a curated per-city split of the monthly cost across
	// spending categories. Keys match the frontend categories; values sum to 1.0.
	ExpenseShares map[string]float64 `json:"expenseShares"`
}

// cities is the in-memory source of truth for Phase 1 (no DB yet).
var cities = []City{
	{
		City:        "Lisbon",
		Country:     "Portugal",
		Region:      "Europe",
		MonthlyCost: 3600,
		Lifestyle:   "Comfortable",
		Description: "Coastal capital with strong healthcare, culture, and walkable neighborhoods.",
		Tags:        []string{"Healthcare", "Walkable", "Coastal", "Expat Friendly"},
		ExpenseShares: map[string]float64{
			"Rent": 0.38, "Food": 0.19, "Travel": 0.10, "Healthcare": 0.13,
			"Utilities": 0.08, "Leisure": 0.08, "Other": 0.04,
		},
	},
	{
		City:        "Porto",
		Country:     "Portugal",
		Region:      "Europe",
		MonthlyCost: 3000,
		Lifestyle:   "Comfortable",
		Description: "Scenic riverside city with lower costs than Lisbon and excellent food.",
		Tags:        []string{"Walkable", "Culture", "Lower Cost", "Healthcare"},
		ExpenseShares: map[string]float64{
			"Rent": 0.34, "Food": 0.21, "Travel": 0.10, "Healthcare": 0.12,
			"Utilities": 0.09, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Valencia",
		Country:     "Spain",
		Region:      "Europe",
		MonthlyCost: 3200,
		Lifestyle:   "Comfortable",
		Description: "Sunny Mediterranean city with beaches, transit, and great quality of life.",
		Tags:        []string{"Beach", "Great Weather", "Transit", "Healthcare"},
		ExpenseShares: map[string]float64{
			"Rent": 0.36, "Food": 0.19, "Travel": 0.11, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.10, "Other": 0.05,
		},
	},
	{
		City:        "Medellín",
		Country:     "Colombia",
		Region:      "Latin America",
		MonthlyCost: 2200,
		Lifestyle:   "Comfortable",
		Description: "Mountain city with mild weather, modern amenities, and a growing expat scene.",
		Tags:        []string{"Low Cost", "Great Weather", "Expat Friendly", "Healthcare"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.13,
			"Utilities": 0.08, "Leisure": 0.10, "Other": 0.05,
		},
	},
	{
		City:        "Mexico City",
		Country:     "Mexico",
		Region:      "North America",
		MonthlyCost: 2800,
		Lifestyle:   "Comfortable",
		Description: "Large cultural hub with world-class food, healthcare, and neighborhoods.",
		Tags:        []string{"Culture", "Healthcare", "Food", "Transit"},
		ExpenseShares: map[string]float64{
			"Rent": 0.33, "Food": 0.22, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.07, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Mérida",
		Country:     "Mexico",
		Region:      "North America",
		MonthlyCost: 2100,
		Lifestyle:   "Lean",
		Description: "Warm, relaxed city known for safety, affordability, and colonial charm.",
		Tags:        []string{"Low Cost", "Warm", "Safety", "Expat Friendly"},
		ExpenseShares: map[string]float64{
			"Rent": 0.28, "Food": 0.23, "Travel": 0.11, "Healthcare": 0.12,
			"Utilities": 0.11, "Leisure": 0.09, "Other": 0.06,
		},
	},
	{
		City:        "Chiang Mai",
		Country:     "Thailand",
		Region:      "Asia",
		MonthlyCost: 1800,
		Lifestyle:   "Lean",
		Description: "Affordable northern Thai city popular with retirees and digital nomads.",
		Tags:        []string{"Low Cost", "Expat Friendly", "Food", "Great Weather"},
		ExpenseShares: map[string]float64{
			"Rent": 0.25, "Food": 0.26, "Travel": 0.14, "Healthcare": 0.11,
			"Utilities": 0.09, "Leisure": 0.10, "Other": 0.05,
		},
	},
	{
		City:        "Penang",
		Country:     "Malaysia",
		Region:      "Asia",
		MonthlyCost: 2300,
		Lifestyle:   "Comfortable",
		Description: "Island city with strong healthcare, beaches, and excellent street food.",
		Tags:        []string{"Healthcare", "Beach", "Food", "Low Cost"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.12, "Healthcare": 0.14,
			"Utilities": 0.09, "Leisure": 0.08, "Other": 0.05,
		},
	},
	{
		City:        "Da Nang",
		Country:     "Vietnam",
		Region:      "Asia",
		MonthlyCost: 1700,
		Lifestyle:   "Lean",
		Description: "Beach city with low living costs, modern apartments, and relaxed pace.",
		Tags:        []string{"Beach", "Low Cost", "Great Weather", "Food"},
		ExpenseShares: map[string]float64{
			"Rent": 0.26, "Food": 0.25, "Travel": 0.14, "Healthcare": 0.10,
			"Utilities": 0.09, "Leisure": 0.11, "Other": 0.05,
		},
	},
	{
		City:        "Panama City",
		Country:     "Panama",
		Region:      "Latin America",
		MonthlyCost: 2900,
		Lifestyle:   "Comfortable",
		Description: "Modern hub with skyline living, healthcare, and retiree visa appeal.",
		Tags:        []string{"Healthcare", "Expat Friendly", "Modern", "Transit"},
		ExpenseShares: map[string]float64{
			"Rent": 0.36, "Food": 0.20, "Travel": 0.11, "Healthcare": 0.13,
			"Utilities": 0.09, "Leisure": 0.07, "Other": 0.04,
		},
	},
	{
		City:        "San Miguel de Allende",
		Country:     "Mexico",
		Region:      "North America",
		MonthlyCost: 3100,
		Lifestyle:   "Premium",
		Description: "Beautiful colonial city with art, restaurants, and a large expat community.",
		Tags:        []string{"Culture", "Expat Friendly", "Walkable", "Premium"},
		ExpenseShares: map[string]float64{
			"Rent": 0.37, "Food": 0.20, "Travel": 0.10, "Healthcare": 0.12,
			"Utilities": 0.07, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Florence",
		Country:     "Italy",
		Region:      "Europe",
		MonthlyCost: 4300,
		Lifestyle:   "Premium",
		Description: "Historic city with world-class art, food, and access to European travel.",
		Tags:        []string{"Culture", "Walkable", "Food", "Premium"},
		ExpenseShares: map[string]float64{
			"Rent": 0.40, "Food": 0.20, "Travel": 0.11, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.07, "Other": 0.03,
		},
	},
	{
		City:        "Bengaluru",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1700,
		Lifestyle:   "Comfortable",
		Description: "Garden city and tech hub with pleasant weather and a large expat crowd.",
		Tags:        []string{"Great Weather", "Expat Friendly", "Modern", "Food"},
		ExpenseShares: map[string]float64{
			"Rent": 0.36, "Food": 0.20, "Travel": 0.11, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Mumbai",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 2200,
		Lifestyle:   "Premium",
		Description: "India's vibrant financial capital by the sea — fast-paced and cosmopolitan.",
		Tags:        []string{"Coastal", "Culture", "Transit", "Premium"},
		ExpenseShares: map[string]float64{
			"Rent": 0.36, "Food": 0.20, "Travel": 0.11, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "New Delhi",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1800,
		Lifestyle:   "Comfortable",
		Description: "The capital, rich in history, food, and connectivity.",
		Tags:        []string{"Culture", "Food", "Transit", "Healthcare"},
		ExpenseShares: map[string]float64{
			"Rent": 0.36, "Food": 0.20, "Travel": 0.11, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Pune",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1500,
		Lifestyle:   "Comfortable",
		Description: "Education and IT city with a mild climate and an easygoing pace.",
		Tags:        []string{"Great Weather", "Culture", "Food", "Low Cost"},
		ExpenseShares: map[string]float64{
			"Rent": 0.32, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.11,
			"Utilities": 0.09, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Hyderabad",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1300,
		Lifestyle:   "Comfortable",
		Description: "Affordable metro famous for biryani, tech, and historic charm.",
		Tags:        []string{"Food", "Low Cost", "Modern", "Culture"},
		ExpenseShares: map[string]float64{
			"Rent": 0.32, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.11,
			"Utilities": 0.09, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Chennai",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1400,
		Lifestyle:   "Comfortable",
		Description: "Coastal metro known for top hospitals, temples, and filter coffee.",
		Tags:        []string{"Healthcare", "Coastal", "Culture", "Food"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.11, "Healthcare": 0.15,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Kochi",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1300,
		Lifestyle:   "Comfortable",
		Description: "Kerala port city with backwaters, healthcare, and a gentle climate.",
		Tags:        []string{"Healthcare", "Coastal", "Great Weather", "Food"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.11, "Healthcare": 0.15,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Goa",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1600,
		Lifestyle:   "Comfortable",
		Description: "Beach state with a relaxed vibe and a thriving expat community.",
		Tags:        []string{"Beach", "Expat Friendly", "Great Weather", "Coastal"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.11, "Other": 0.05,
		},
	},
	{
		City:        "Chandigarh",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1400,
		Lifestyle:   "Comfortable",
		Description: "Clean, planned city with wide streets and high quality of life.",
		Tags:        []string{"Walkable", "Safety", "Modern", "Great Weather"},
		ExpenseShares: map[string]float64{
			"Rent": 0.32, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.11,
			"Utilities": 0.09, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Pondicherry",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1200,
		Lifestyle:   "Comfortable",
		Description: "Seaside town with French-quarter charm and an expat scene.",
		Tags:        []string{"Beach", "Expat Friendly", "Coastal", "Walkable"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.11, "Other": 0.05,
		},
	},
	{
		City:        "Visakhapatnam",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1050,
		Lifestyle:   "Comfortable",
		Description: "Beach city between hills and sea with a laid-back feel.",
		Tags:        []string{"Beach", "Coastal", "Great Weather", "Low Cost"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.08, "Leisure": 0.11, "Other": 0.05,
		},
	},
	{
		City:        "Shillong",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Comfortable",
		Description: "Misty hill station with cool weather and a vibrant music culture.",
		Tags:        []string{"Great Weather", "Culture", "Walkable", "Low Cost"},
		ExpenseShares: map[string]float64{
			"Rent": 0.29, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.11,
			"Utilities": 0.12, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Udaipur",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Comfortable",
		Description: "Romantic city of lakes and palaces with a relaxed pace.",
		Tags:        []string{"Culture", "Walkable", "Low Cost", "Great Weather"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Kolkata",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Lean",
		Description: "Cultural heart of India with literature, art, and low living costs.",
		Tags:        []string{"Culture", "Low Cost", "Food", "Transit"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Jaipur",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Lean",
		Description: "Pink City of palaces, heritage, and affordable living.",
		Tags:        []string{"Culture", "Low Cost", "Walkable", "Food"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Ahmedabad",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Lean",
		Description: "Heritage city with great food and a very low cost of living.",
		Tags:        []string{"Low Cost", "Food", "Culture", "Safety"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Coimbatore",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1000,
		Lifestyle:   "Lean",
		Description: "Calm South Indian city known for hospitals and pleasant weather.",
		Tags:        []string{"Healthcare", "Low Cost", "Great Weather", "Safety"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.11, "Healthcare": 0.15,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Mysuru",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1000,
		Lifestyle:   "Lean",
		Description: "Royal heritage city with a slow pace and clean surroundings.",
		Tags:        []string{"Culture", "Low Cost", "Walkable", "Safety"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Thiruvananthapuram",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Lean",
		Description: "Green Kerala capital by the coast with strong healthcare.",
		Tags:        []string{"Healthcare", "Coastal", "Great Weather", "Low Cost"},
		ExpenseShares: map[string]float64{
			"Rent": 0.30, "Food": 0.22, "Travel": 0.11, "Healthcare": 0.15,
			"Utilities": 0.08, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Dehradun",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1100,
		Lifestyle:   "Lean",
		Description: "Himalayan foothill city with cool air and a calm setting.",
		Tags:        []string{"Great Weather", "Low Cost", "Safety", "Walkable"},
		ExpenseShares: map[string]float64{
			"Rent": 0.29, "Food": 0.22, "Travel": 0.12, "Healthcare": 0.11,
			"Utilities": 0.12, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Indore",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1000,
		Lifestyle:   "Lean",
		Description: "India's cleanest city, famous for street food and value.",
		Tags:        []string{"Low Cost", "Food", "Safety", "Walkable"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Nagpur",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 950,
		Lifestyle:   "Lean",
		Description: "Central, affordable city known for oranges and easy living.",
		Tags:        []string{"Low Cost", "Warm", "Safety", "Transit"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Lucknow",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1000,
		Lifestyle:   "Lean",
		Description: "City of Nawabs with refined cuisine and rich culture.",
		Tags:        []string{"Culture", "Food", "Low Cost", "Walkable"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Bhubaneswar",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 950,
		Lifestyle:   "Lean",
		Description: "Temple city that's affordable, green, and well-planned.",
		Tags:        []string{"Low Cost", "Culture", "Safety", "Walkable"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
	{
		City:        "Surat",
		Country:     "India",
		Region:      "Asia",
		MonthlyCost: 1050,
		Lifestyle:   "Lean",
		Description: "Fast-growing, safe business city with great food and low costs.",
		Tags:        []string{"Low Cost", "Food", "Safety", "Modern"},
		ExpenseShares: map[string]float64{
			"Rent": 0.27, "Food": 0.25, "Travel": 0.13, "Healthcare": 0.11,
			"Utilities": 0.10, "Leisure": 0.09, "Other": 0.05,
		},
	},
}
